config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount Spree::Core::Engine, :at => '/'

  resources :snippets
  root to: "snippets#new"
  mount Sidekiq::Web, at: "/sidekiq"

  Spree::Core::Engine.add_routes do
    namespace :admin do
      get '/featured_products', :to => 'featured_products#index'
      put '/featured_products/:id', :to => 'featured_products#update', :as => 'featured_product'

      get '/site_regist', :to => 'site_regist#index'

      resources :sites do
        member do
          post 'scrap'

        end
        resources :site_urls

      end

      resources :scrap_histories

    end

    get '/account/collections', :to => 'users#collections', :as => 'user_collections'
    delete '/account/collections/:id', :to => 'users#collection_delete'
    get '/account/profits', :to => 'users#profits'
  end

  get '/collections', :to => 'collections#index'
  get '/collections/:id', :to => 'collections#show', :as => 'collection_show'
  post '/collections', :to => 'collections#create'

  get '/site_regist', :to => 'site_regist#index'
  get '/site_regist/new', :to => 'site_regist#new'
  post '/site_regist', :to => 'site_regist#create'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 10.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user, :class_name => "Spree::User"
  has_many :collection_items
end

app/models/collection_item.rb
class CollectionItem < ActiveRecord::Base
  belongs_to :product, :class_name => "Spree::Product"
  belongs_to :user, :class_name => "Spree::User"
  belongs_to :collection
end

app/models/collection_profit.rb
class CollectionProfit < ActiveRecord::Base
  belongs_to :line_item, :class_name => 'Spree::LineItem', :foreign_key => :spree_line_item_id
  # belongs_to :variant, :class_name => 'Spree::Variant', :through => :line_item, :foreign_key => :spree_variant_id

end

app/models/image_decorator.rb
Spree::Image.class_eval do
	attachment_definitions[:attachment][:styles] = {
    	:mini => '75.8x96.8>', # thumbs under image
    	:small => '100x100>', # images on category view
    	:product => '304x381>', # full product image
    	:large => '550x690>' # light box image
  	}
end

app/models/order_decorator.rb
Spree::Address.class_eval do
  def require_zipcode?
      false
  end
end

app/models/scrap_history.rb
class ScrapHistory < ActiveRecord::Base
  belongs_to :site
end

app/models/site.rb
class Site < ActiveRecord::Base
  validates :name, presence: true
  validates :url, presence: true

  has_many :site_url, :dependent => :destroy
end

app/models/site_regist.rb
class SiteRegist < ActiveRecord::Base
end

app/models/site_url.rb
class SiteUrl < ActiveRecord::Base
  validates :taxon_id, presence: true
  validates :url, presence: true

  belongs_to :site

end

app/models/spree/featured_product.rb
module Spree
  class FeaturedProduct < Spree::Product

    
  end
end

app/models/spree/price_decorator.rb
Spree::Price.class_eval do
  # def price
  #   amount / 1164
  # end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_and_belongs_to_many :collections
  # default_scope { where(is_open: true) }
  add_simple_scopes ([
       :descend_by_created_at
  ])

  add_search_scope :in_taxon do |taxon|

    includes(:classifications).
    where("spree_products_taxons.taxon_id" => taxon.self_and_descendants.pluck(:id))
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  def applicable_filters
    fs = []
    # fs << ProductFilters.taxons_below(self)
    ## unless it's a root taxon? left open for demo purposes

    fs << Spree::Core::ProductFilters.price_filter if Spree::Core::ProductFilters.respond_to?(:price_filter)
    # fs << Spree::Core::ProductFilters.brand_filter if Spree::Core::ProductFilters.respond_to?(:brand_filter)
    fs
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/collections_controller.rb
class CollectionsController < Spree::StoreController

  def index
    @collections = Collection.all
  end

  def show
    curr_page = params[:page] || 1
    @collection = Collection.find(params[:id])
    @collection_items = CollectionItem.where(:collection_id => params[:id]).page(curr_page).per(12)
  end

  def create
    collection = Collection.where(:user_id => spree_current_user.id).first

    collection = Collection.create(:user_id => spree_current_user.id) unless collection

    collection_item = CollectionItem.where(:product_id => params[:id], :collection_id => collection.id)

    if collection_item.count > 0
      @is_error = false
      @is_dup = true
    else
      collection_item = CollectionItem.new
      collection_item.user_id = spree_current_user.id
      collection_item.product_id = params[:id]
      collection_item.collection_id = collection.id

      if collection_item.save
        @is_error = false
        @is_dup = false
      else
        @is_error = true
        @is_dup = false
      end
    end
  end

end

app/controllers/site_regist_controller.rb
class SiteRegistController < Spree::StoreController
  def index
  end

  def new
    @site_regist = SiteRegist.new
  end

  def create
    @site_regist = SiteRegist.new(article_params)

    respond_to do |format|
      if @site_regist.save
        format.html { redirect_to '/site_regist', notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def article_params
    params.require(:site_regist).permit(:email, :url, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/spree/admin/general_settings/edit.html.erb
<% content_for :page_title do %>
  기본설정
<% end %>

<%= form_tag admin_general_settings_path, method: :put do %>
  <div id="preferences" data-hook>

    <fieldset class="general no-border-top">

      <%= fields_for :store do |f| %>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_name">
              <%= f.label '사이트이름' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_seo_title">
              <%= f.label 'SEO 타이틀' %>
              <%= f.text_field :seo_title, class: 'form-control'  %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_meta_keywords">
              <%= f.label '메타키워드' %>
              <%= f.text_field :meta_keywords, class: 'form-control'  %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_meta_description">
              <%= f.label '메타 설명' %>
              <%= f.text_field :meta_description, class: 'form-control'  %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_input_url">
              <%= f.label '사이트 주소' %>
              <%= f.text_field :url, class: 'form-control'  %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group" data-hook="admin_general_setting_mail_from_address">
              <%= f.label '이메일' %>
              <%= f.text_field :mail_from_address, class: 'form-control'  %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div class="col-md-6">

          <%#-------------------------------------------------%>
          <%# Security settings                               %>
          <%#-------------------------------------------------%>
          <div class="panel panel-default security">
            <div class="panel-heading">
              <h1 class="panel-title">
                보안설정
              </h1>
            </div>

            <div class="panel-body">
              <% @preferences_security.each do |key|
                  type = Spree::Config.preference_type(key) %>
                  <div class="checkbox">
                    <%= label_tag key do %>
                      <%= preference_field_tag(key, Spree::Config[key], type: type) %>
                      <%= Spree.t(key) %>
                    <% end %>
                  </div>
              <% end %>
            </div>
          </div>

          <%#-------------------------------------------------%>
          <%# Clear cache                                     %>
          <%#-------------------------------------------------%>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title">캐쉬청소</h1>
            </div>

            <div class="panel-body">
              <div class="clear-cache-warning alert alert-warning">
                <%#= Spree.t(:clear_cache_warning) %>
                캐쉬를 청소하면 일시적으로 사이트가 느려질수 있습니다.
              </div>
              <div data-hook="general_settings_clear_cache">
                <%= button '캐쉬청소', 'ok', 'button', id: "clear_cache" %>
              </div>
            </div>
          </div>

        </div>
        <div class="col-md-6">

          <%#-------------------------------------------------%>
          <%# Currency Settings                               %>
          <%#-------------------------------------------------%>
          <div class="panel panel-default currency">
            <div class="panel-heading">
              <h1 class="panel-title">
                통화설정
              </h1>
            </div>

            <div class="panel-body">
              <div class="form-group">
                <%= label_tag :currency, '통화를 선택하세요' %>
                <%= select_tag :currency, currency_options %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="form-actions" data-hook="buttons">
        <%= button '저장', 'save' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= button_link_to '취소', edit_admin_general_settings_url, icon: 'delete' %>
      </div>

    </fieldset>

  </div>

<% end %>

<script>
  $('#store_default_currency').select2();
  $('#currency').select2();
</script>

app/views/spree/admin/images/_form.html.erb
<div data-hook="admin_image_form_fields" class="row">
  <div class="col-md-6">
    <div data-hook="file" class="form-group">
      <%= f.label :attachment, '파일명' %>
      <%= f.file_field :attachment %>
    </div>
    <div data-hook="variant" class="form-group">
      <%= f.label :viewable_id, '옵션' %>
      <%= f.select :viewable_id, @variants, {}, {:class => 'select2'} %>
    </div>
  </div>
  <div data-hook="alt_text" class="col-md-6">
    <div class="form-group">
      <%= f.label :alt, '대체문구' %>
      <%= f.text_area :alt, :rows => 4, :class => 'form-control' %>
    </div>
  </div>
</div>

app/views/spree/admin/images/edit.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :images } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @image } %>

<%= form_for [:admin, @product, @image], html: { multipart: true } do |f| %>
  <div data-hook="edit_image" class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= @image.attachment_file_name%>
      </h1>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div data-hook="thumbnail" class="col-md-3 text-center">
          <%= f.label Spree.t(:thumbnail) %>
          <%= link_to image_tag(@image.attachment.url(:small)), @image.attachment.url(:product) %>
        </div>
        <div class="col-md-9">
          <%= render partial: 'form', locals: { f: f } %>
        </div>

        <div class="form-actions" data-hook="buttons">
          <%= button '저장', 'save' %>
          <span class="or"><%= Spree.t(:or) %></span>
          <%= button_link_to '취소', spree.admin_product_images_url(@product), id: 'cancel_link', icon: 'delete' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/spree/admin/images/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :images } %>

<% content_for :page_actions do %>
  <%= button_link_to('새 이미지', spree.new_admin_product_image_url(@product), { class: "btn-success", icon: 'add', id: 'new_image_link' }) if can? :create, Spree::Image %>
<% end %>

<% has_variants = @product.has_variants? %>

<% unless @product.variant_images.any? %>
  <div class="alert alert-warning">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Image)) %>.
  </div>
<% else %>
  <table class="table sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_product_images_url(@product) %>">
    <thead>
      <tr data-hook="images_header">
        <th colspan="2">
          썸네일
        </th>
        <% if has_variants %>
          <th>
            옵션
          </th>
        <% end %>
        <th>
          대체 문구
        </th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@product.variant_images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row">
          <td class="move-handle text-center">
            <% if can? :edit, image %>
              <span class="icon icon-move handle"></span>
            <% end %>
          </td>
          <td class="image">
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:product) %>
          </td>
          <% if has_variants %>
            <td><%= options_text_for(image) %></td>
          <% end %>
          <td><%= image.alt %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_with_icon('edit', Spree.t(:edit), spree.edit_admin_product_image_url(@product, image), class: 'btn btn-primary btn-sm', no_text: true, data: { action: 'edit' }) if can? :edit, image %>
            <%= link_to_delete(image, { url: spree.admin_product_image_url(@product, image), no_text: true }) if can? :destroy, image %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/images/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product } %>

<% content_for :page_title do %>
  새 이미지
<% end %>

<%= form_for [:admin, @product, @image], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_image">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button '저장', 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to '취소', spree.admin_product_images_url(@product), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  주문
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to '새 주문', new_admin_order_url, :class => "btn-success", :icon => 'add', :id => 'admin_new_order' %>
<% end if can? :create, Spree::Order %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="date-range-filter col-md-8">
          <div class="form-group">
            <%= label_tag :q_created_at_gt, '날짜' %>
            <div class="row no-padding-bottom">
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from form-control', :value => params[:q][:created_at_gt], :placeholder => '시작' %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>

              </div>
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to form-control', :value => params[:q][:created_at_lt], :placeholder => '마지막' %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_number_cont, '주문 번호' %>
            <%= f.text_field :number_cont, class: 'form-control js-quick-search-target' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_state_eq, '상태' %>
            <%= f.select :state_eq, Spree::Order.state_machines[:state].states.map {|s| [Spree.t("order_state.#{s.name}"), s.value]}, {:include_blank => true}, :class => 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_payment_state_eq, '결제상태' %>
            <%= f.select :payment_state_eq, Spree::Order::PAYMENT_STATES.map {|s| [Spree.t("payment_states.#{s}"), s]}, {:include_blank => true}, :class => 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_shipment_state_eq, '배송상태' %>
            <%= f.select :shipment_state_eq, Spree::Order::SHIPMENT_STATES.map {|s| [Spree.t("shipment_states.#{s}"), s]}, {:include_blank => true}, :class => 'select2 js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_firstname_start, '시작 이름' %>
            <%= f.text_field :bill_address_firstname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_lastname_start, '마지막 이름' %>
            <%= f.text_field :bill_address_lastname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_email_cont, '이메일' %>
            <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_line_items_variant_id_in, Spree.t(:sku) %>
            <%= f.select :line_items_variant_id_in, Spree::Variant.having_orders.order(:sku).pluck(:sku, :id), {:include_blank => true}, :class => 'select2' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_promotions_id_in, '프로모션' %>
            <%= f.select :promotions_id_in, Spree::Promotion.applied.pluck(:name, :id), {:include_blank => true}, :class => 'select2' %>
          </div>
        </div>

        <div class="col-md-4">

          <div class="form-group">

            <div class="checkbox">
              <%= label_tag 'q_completed_at_not_null' do %>
                <%= f.check_box :completed_at_not_null, {:checked => @show_only_completed}, '1', '0' %>
                <%= '완료된 주문만 조회' %>
              <% end %>
            </div>

            <!-- <div class="checkbox">
              <%= label_tag 'q_considered_risky_eq' do %>
                <%= f.check_box :considered_risky_eq, {:checked => (params[:q][:considered_risky_eq] == '1')}, '1', '' %>
                <%= Spree.t(:show_only_considered_risky) %>
              <% end %>
            </div> -->

          </div>

        </div>

      </div>

      <div data-hook="admin_orders_index_search_buttons" class="form-actions">
        <%= button '검색', 'search' %>
      </div>

    <% end %>

  </div>

<% end %>

<%= render :partial => 'spree/admin/shared/index_table_options', :locals => { :collection => @orders } %>

<% if @orders.any? %>
  <table class="table" id="listing_orders" data-hook>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at,   '완료날짜' %></th>
        <% else %>
          <th><%= sort_link @search, :created_at,     '주문날짜' %></th>
        <% end %>
        <th><%= sort_link @search, :number,           '주문번호' %></th>
        <!-- <th><%= sort_link @search, :considered_risky, I18n.t(:considered_risky, :scope => 'activerecord.attributes.spree/order') %></th> -->
        <th><%= sort_link @search, :state,            '상태' %></th>
        <th><%= sort_link @search, :payment_state,    '결제상태' %></th>
         <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <th><%= sort_link @search, :shipment_state, '배송상태' %></th>
         <% end %>
        <th><%= sort_link @search, :email,            '이메일' %></th>
        <th><%= sort_link @search, :total,            '주문금액' %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
        <td><%= l (@show_only_completed ? order.completed_at : order.created_at).try(&:to_date) %></td>
        <td><%= link_to order.number, edit_admin_order_path(order) %></td>
        <!-- <td>
          <span class="label label-<%= order.considered_risky ? 'considered_risky' : 'considered_safe' %>">
            <%= order.considered_risky ? Spree.t("risky") : Spree.t("safe") %>
          </span>
        </td> -->
        <td>
          <span class="label label-<%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span>
          <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= order.state %>"></span>
        </td>
        <td>
          <% if order.payment_state %>
            <span class="label label-<%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) %></span>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_payment_state_eq" data-ransack-value="<%= order.payment_state %>"></span>
          <% end %>
        </td>
        <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <td>
            <% if order.shipment_state %>
              <span class="label label-<%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") %></span>
              <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_shipment_state_eq" data-ransack-value="<%= order.shipment_state %>"></span>
            <% end %>
          </td>
        <% end %>
        <td>
          <% if order.user %>
            <%= link_to order.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= mail_to order.email %>
          <% end %>
          <% if order.user || order.email %>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_email_cont" data-ransack-value="<%= order.email %>"></span>
          <% end %>
        </td>
        <td><%= order.display_total.to_html %></td>
        <td class='actions actions-1' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
    <%= link_to(Spree.t(:add_one), new_admin_order_url) if can? :create, Spree::Order %>!
  </div>
<% end %>

<%= render :partial => 'spree/admin/shared/index_table_options', :locals => { :collection => @orders, :simple => true } %>

app/views/spree/admin/promotions/new.html.erb
<% content_for :page_title do %>
  새 프로모션
<% end %>

<%= form_for :promotion, :url => collection_url do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <div class="text-center">
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </div>
<% end %>

app/views/spree/admin/reviews/index.html.erb
<% content_for :page_title do %>
	리뷰
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_reviews_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_name_cont, '사용자' %>
						<%= f.text_field :name_cont, size: 25, class: 'form-control' %>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_title_cont, '제목' %>
						<%= f.text_field :title_cont, size: 25, class: 'form-control' %>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_review_cont, '컨텐츠' %>
						<%= f.text_field :review_cont, size: 25, class: 'form-control' %>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_approved_eq, '승인상태' %>
						<%= f.select :approved_eq, [[Spree.t(:all), nil], [Spree.t(:approved_reviews), true], [Spree.t(:unapproved_reviews), false]], {}, class: 'select2' %>
					</div>
				</div>
			</div>
			<div class="form-actions" data-hook="admin_reviews_index_search_buttons">
				<%= button '검색', 'search' %>
			</div>
    <% end %>
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @reviews %>

<% if @reviews.any? %>
	<table class="table" id="listing_reviews">
		<thead>
			<tr>
				<th><%= sort_link @search, :product, '상품' %></th>
				<th><%= sort_link @search, :rating, '평가' %></th>
				<th>피드백</th>
				<th><%= sort_link @search, :user, '사용자' %></th>
				<th><%= sort_link @search, :ip_address, 'IP주소' %></th>
				<th><%= sort_link @search, :created_at, '작성일' %></th>
				<th data-hook="admin_reviews_index_header_actions" class="actions"></th>
			</tr>
		</thead>
		<tbody>
			<% @reviews.each do |review| %>
				<tr data-hook="admin_reviews_index_rows" id="<%= dom_id review %>" class="<%= cycle('odd', 'even') %>">
					<td><%= link_to_if review.product, review.product.name, product_path(review.product) %></td>
					<td><%= review.rating %>/5</td>
					<td><%= link_to "(#{review.feedback_stars}/#{review.feedback_reviews.size})", admin_review_feedback_reviews_path(review) %></td>
					<td><%= review.user_id ? link_to(review.user.try(:email), [:admin, review.user]) : Spree.t(:anonymous) %></td>
					<td><%= link_to_if review.ip_address, review.ip_address, "http://whois.domaintools.com/#{review.ip_address}", target: :blank %></td>
					<td><%= l review.created_at, format: :short %></td>
					<td data-hook="admin_reviews_index_row_actions" class="actions">
						<%= link_to_with_icon 'save', Spree.t(:approve), approve_admin_review_url(review), no_text: true, class: 'approve btn btn-default' unless review.approved %>
						<%= link_to_edit review, no_text: true, class: 'edit' %>
						<%= link_to_delete review, no_text: true %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<div class="alert alert-info no-objects-found">
		<%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/review')) %>
	</div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @reviews %>