config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount Spree::Core::Engine, :at => '/'

  resources :snippets
  root to: "snippets#new"
  mount Sidekiq::Web, at: "/sidekiq"

  Spree::Core::Engine.add_routes do
    namespace :admin do
      get '/featured_products', :to => 'featured_products#index'
      put '/featured_products/:id', :to => 'featured_products#update', :as => 'featured_product'

      get '/site_regist', :to => 'site_regist#index'

      resources :sites do
        member do
          post 'scrap'

        end
        resources :site_urls

      end

      resources :scrap_histories

    end

    get '/account/collections', :to => 'users#collections', :as => 'user_collections'
    delete '/account/collections/:id', :to => 'users#collection_delete'
    get '/account/profits', :to => 'users#profits'
  end

  get '/collections', :to => 'collections#index'
  get '/collections/:id', :to => 'collections#show', :as => 'collection_show'
  post '/collections', :to => 'collections#create'

  get '/site_regist', :to => 'site_regist#index'
  get '/site_regist/new', :to => 'site_regist#new'
  post '/site_regist', :to => 'site_regist#create'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 10.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user, :class_name => "Spree::User"
  has_many :collection_items
end

app/models/collection_item.rb
class CollectionItem < ActiveRecord::Base
  belongs_to :product, :class_name => "Spree::Product"
  belongs_to :user, :class_name => "Spree::User"
  belongs_to :collection
end

app/models/collection_profit.rb
class CollectionProfit < ActiveRecord::Base
  belongs_to :line_item, :class_name => 'Spree::LineItem', :foreign_key => :spree_line_item_id
  # belongs_to :variant, :class_name => 'Spree::Variant', :through => :line_item, :foreign_key => :spree_variant_id

end

app/models/image_decorator.rb
Spree::Image.class_eval do
	attachment_definitions[:attachment][:styles] = {
    	:mini => '75.8x96.8>', # thumbs under image
    	:small => '100x100>', # images on category view
    	:product => '304x381>', # full product image
    	:large => '550x690>' # light box image
  	}
end

app/models/order_decorator.rb
Spree::Address.class_eval do
  def require_zipcode?
      false
  end
end

app/models/scrap_history.rb
class ScrapHistory < ActiveRecord::Base
  belongs_to :site
end

app/models/site.rb
class Site < ActiveRecord::Base
  validates :name, presence: true
  validates :url, presence: true

  has_many :site_url, :dependent => :destroy
end

app/models/site_regist.rb
class SiteRegist < ActiveRecord::Base
end

app/models/site_url.rb
class SiteUrl < ActiveRecord::Base
  validates :taxon_id, presence: true
  validates :url, presence: true

  belongs_to :site

end

app/models/spree/featured_product.rb
module Spree
  class FeaturedProduct < Spree::Product

    
  end
end

app/models/spree/price_decorator.rb
Spree::Price.class_eval do
  # def price
  #   amount / 1164
  # end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_and_belongs_to_many :collections
  # default_scope { where(is_open: true) }
  add_simple_scopes ([
       :descend_by_created_at
  ])

  add_search_scope :in_taxon do |taxon|

    includes(:classifications).
    where("spree_products_taxons.taxon_id" => taxon.self_and_descendants.pluck(:id))
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  def applicable_filters
    fs = []
    # fs << ProductFilters.taxons_below(self)
    ## unless it's a root taxon? left open for demo purposes

    fs << Spree::Core::ProductFilters.price_filter if Spree::Core::ProductFilters.respond_to?(:price_filter)
    # fs << Spree::Core::ProductFilters.brand_filter if Spree::Core::ProductFilters.respond_to?(:brand_filter)
    fs
  end
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  has_and_belongs_to_many :option_values, join_table: :spree_option_values_variants, class_name: "Spree::OptionValue"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/collections_controller.rb
class CollectionsController < Spree::StoreController

  def index
    @collections = Collection.all
  end

  def show
    curr_page = params[:page] || 1
    @collection = Collection.find(params[:id])
    @collection_items = CollectionItem.where(:collection_id => params[:id]).page(curr_page).per(12)
  end

  def create
    collection = Collection.where(:user_id => spree_current_user.id).first

    collection = Collection.create(:user_id => spree_current_user.id) unless collection

    collection_item = CollectionItem.where(:product_id => params[:id], :collection_id => collection.id)

    if collection_item.count > 0
      @is_error = false
      @is_dup = true
    else
      collection_item = CollectionItem.new
      collection_item.user_id = spree_current_user.id
      collection_item.product_id = params[:id]
      collection_item.collection_id = collection.id

      if collection_item.save
        @is_error = false
        @is_dup = false
      else
        @is_error = true
        @is_dup = false
      end
    end
  end

end

app/controllers/site_regist_controller.rb
class SiteRegistController < Spree::StoreController
  def index
  end

  def new
    @site_regist = SiteRegist.new
  end

  def create
    @site_regist = SiteRegist.new(article_params)

    respond_to do |format|
      if @site_regist.save
        format.html { redirect_to '/site_regist', notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def article_params
    params.require(:site_regist).permit(:email, :url, :description)
  end
end

app/controllers/spree/admin/featured_products_controller.rb
class Spree::Admin::FeaturedProductsController < Spree::Admin::ProductsController
  #  helper 'spree/products'
  #  helper_method :clone_object_url
  #
  def index
    session[:return_to] = request.url
    @taxonomies = Spree::Taxonomy.includes(root: :children)
    respond_with(@collection)
  end

  def collection
    return @collection if @collection.present?
    params[:q] ||= {}
    params[:q][:deleted_at_null] ||= "1"

    params[:q][:s] ||= "name asc"

    taxon = Spree::Taxon.find(params[:taxon]) if params[:taxon]

    if taxon
      @collection = super.in_taxon(taxon).only_featured
    else
      @collection = super.only_featured
    end

    if params[:q].delete(:deleted_at_null) == '0'
      @collection = @collection.with_deleted
    end
    # @search needs to be defined as this is passed to search_form_for
    @search = @collection.ransack(params[:q])
    @collection = @search.result.
          distinct_by_product_ids(params[:q][:s]).
          includes(product_includes).
          page(params[:page]).
          per(params[:per_page] || Spree::Config[:admin_products_per_page])

    @collection
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/spree/admin/featured_products/_featured_switch.html.erb
<td>
	<div class="switch_error">
		<span class="glyphicon glyphicon-exclamation-sign text-danger lead" data-toggle="tooltip"
              data-placement="top" title="<%= Spree.t(:featured_ajax_error) %>"></span>
	</div>

	<%= form_for [:admin, product], :method => :put do |f| %>
		<%= f.check_box :featured, class: 'switch_me', id: "#{product.id}" %>
	<% end %>
</td>

app/views/spree/admin/featured_products/index.html.erb
<% content_for :page_title do %>
  피처드 상품
<% end %>



<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = {:f => f} %>
      <div data-hook="admin_products_index_search" class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name_cont, '상품명' %>
            <%= f.text_field :name_cont, :size => 15, class: "form-control js-quick-search-target" %>
          </div>
        </div>
        <div class="col-md-6" >
          <div class="form-group">
            <%= f.label :variants_including_master_sku_cont, Spree.t(:sku) %>
            <%= f.text_field :variants_including_master_sku_cont, :size => 15, class: "form-control" %>
          </div>
        </div>




        <div class="col-md-12">
          <div class="field checkbox">
            <label>
              <%= f.check_box :deleted_at_null, {:checked => params[:q][:deleted_at_null] == '0'}, '0', '1' %>
              삭제된 상품 포함
            </label>
          </div>
        </div>
      </div>
      <div data-hook="admin_products_index_search_buttons" class="form-actions">
        <%= button '검색', 'search' %>
      </div>
    <% end %>

  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

<% if @collection.any? %>
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:sku) %></th>
        <th colspan="2"><%= sort_link @search,:name, Spree.t(:name), { default_order: "desc" }, {title: 'admin_products_listing_name_title'} %></th>
        <th class="text-center">
          <%= sort_link @search, :master_default_price_amount, Spree.t(:master_price), {}, {title: 'admin_products_listing_price_title'} %>
        </th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |product| %>
          <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="sku"><%= product.sku rescue '' %></td>
            <td class="image"><%= mini_image product %></td>
            <td><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
            <td class="text-center"><%= product.display_price.to_html rescue '' %></td>
            <td class="actions actions-3 text-right" data-hook="admin_products_index_row_actions">
              <%#= link_to_edit product, no_text: true, class: 'edit' if can?(:edit, product) && !product.deleted? %>
              <%#= link_to_clone product, no_text: true, class: 'clone' if can?(:clone, product) %>
              <%#= link_to_delete product, no_text: true if can?(:delete, product) && !product.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    피처드 상품이 존재하지 않습니다.
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>